services:
  etcd-1:
      container_name: etcd-1
      image: quay.io/coreos/etcd:v3.5.21
      entrypoint: /usr/local/bin/etcd
      ports:
          - "23791:2379"
      command:
        - '--name=etcd-1'
        - '--data-dir=/etcd_data'
        - '--initial-advertise-peer-urls=http://etcd-1:2380'
        - '--listen-peer-urls=http://0.0.0.0:2380'
        - '--listen-client-urls=http://0.0.0.0:2379'
        - '--advertise-client-urls=http://etcd-1:2379'
        - '--initial-cluster=etcd-1=http://etcd-1:2380,etcd-2=http://etcd-2:2380,etcd-3=http://etcd-3:2380'
        - '--initial-cluster-state=new'
        - '--initial-cluster-token=ct_hw4a_etcd'
      volumes:
        - ./etcd/etcd-1:/etcd_data

  etcd-2:
      container_name: etcd-2
      image: quay.io/coreos/etcd:v3.5.21
      entrypoint: /usr/local/bin/etcd
      ports:
          - "23792:2379"
      command:
        - '--name=etcd-2'
        - '--data-dir=/etcd_data'
        - '--initial-advertise-peer-urls=http://etcd-2:2380'
        - '--listen-peer-urls=http://0.0.0.0:2380'
        - '--listen-client-urls=http://0.0.0.0:2379'
        - '--advertise-client-urls=http://etcd-2:2379'
        - '--initial-cluster=etcd-1=http://etcd-1:2380,etcd-2=http://etcd-2:2380,etcd-3=http://etcd-3:2380'
        - '--initial-cluster-state=new'
        - '--initial-cluster-token=ct_hw4a_etcd'
      volumes:
        - ./etcd/etcd-2:/etcd_data
  
  etcd-3:
      container_name: etcd-3
      image: quay.io/coreos/etcd:v3.5.21
      entrypoint: /usr/local/bin/etcd
      ports:
          - "23793:2379"
      command:
        - '--name=etcd-3'
        - '--data-dir=/etcd_data'
        - '--initial-advertise-peer-urls=http://etcd-3:2380'
        - '--listen-peer-urls=http://0.0.0.0:2380'
        - '--listen-client-urls=http://0.0.0.0:2379'
        - '--advertise-client-urls=http://etcd-3:2379'
        - '--initial-cluster=etcd-1=http://etcd-1:2380,etcd-2=http://etcd-2:2380,etcd-3=http://etcd-3:2380'
        - '--initial-cluster-state=new'
        - '--initial-cluster-token=ct_hw4a_etcd'
      volumes:
        - ./etcd/etcd-3:/etcd_data

  controller:
    container_name: controller
    build:
      context: .
      dockerfile: ./cmd/controller/Dockerfile
    ports:
      - "8080:8080"
    networks:
      - temp
    environment:
      - DOCKER_NETWORK=temp
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    tty: true
    stdin_open: true

  loadbalancer:
    container_name: loadbalancer
    build:
      context: .
      dockerfile: ./cmd/loadbalancer/Dockerfile
    ports:
      - "9001:9001"
    networks:
      - temp
    depends_on:
      controller:
        condition: service_started

  node:
    image: ct_hw4a-node:latest
    build:
      context: .
      dockerfile: ./cmd/node/Dockerfile
    profiles:
      - build_only
  
  client:
    image: ct_hw4a-client:latest
    build:
      context: .
      dockerfile: ./cmd/client/Dockerfile
    profiles:
      - build_only

networks:
  temp:
    driver: bridge